### ISSUE TITLE
RecordTableページに表示する表の作成

### ISSUE THREAD

**Issue by miz8462** [miz8462/insomnia_record#2]
# 表の作成
## デイリーデータの表示
一日分のデータを縦に表示する
- 日付
- 睡眠データ
- 睡眠サマリー
    - 総臥床時間: (起床時間 - 就寝時間)
    - 総睡眠時間: (総臥床時間 - (寝付くまでの時間 + 目覚めてた時間))
    - 睡眠効率: (総睡眠時間 / 総臥床時間 * 100)

## 各データの週間平均の表示
表の右側に一週間分（最新七日分）の平均を表示

**Comment by miz8462** [comment]
テーブルの作成、日付、睡眠データの表示完了

## TODO

- [x] 日付を MM/DD の形で表示する
- [x] 睡眠サマリーの関数を作る
  - [x] テーブルに表示する
- [x] テーブルに仮データを表示する
  - [x] 七日間平均を求める関数を作る
- [x] 睡眠データが７未満の場合Rangeエラーになる
- [x] 新しいデータを7つ表示するように修正、現状は古いのから7つ
- [x]  テーブル画面に登録画面に戻るボタンを実装する
- [x]  新しいデータを登録せずに表を見るだけのボタンを登録ボタンの下に実装する
- [x] 日付をタップしたら「修正」「削除」できるモーダルが開くようにする

**Comment by miz8462** [comment]
睡眠データが７未満の場合Rangeエラーになる

**Comment by miz8462** [comment]
- [ ] 登録画面に戻るボタン

**Comment by miz8462** [comment]
- [] 新しいデータを登録せずに表を見るだけのボタンを登録ボタンの下に実装する
